# Generated by Django 5.0.6 on 2024-06-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("age", models.IntegerField(verbose_name="Age")),
                ("address", models.CharField(max_length=50, verbose_name="Address")),
                (
                    "grade",
                    models.TextField(
                        choices=[
                            ("Distinction", "A+"),
                            ("Division I", "A"),
                            ("Division II", "B"),
                            ("Division III", "C"),
                            ("Fail", "F"),
                        ],
                        verbose_name="Grade",
                    ),
                ),
                ("major", models.CharField(max_length=50, verbose_name="Major")),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
    ]
